# Generated by Django 3.1.1 on 2020-11-15 21:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('type', models.CharField(choices=[('Manga', 'Manga'), ('Manhwa', 'Manhwa'), ('Manhua', 'Manhua'), ('Webtoon', 'Webtoon'), ('Anime', 'Anime')], max_length=7, null=True)),
                ('date', models.DateField(default=datetime.datetime(2020, 11, 15, 21, 32, 1, 588135, tzinfo=utc))),
            ],
        ),
    ]
