# Generated by Django 3.1.2 on 2021-02-09 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weeb', '0003_auto_20201118_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 9, 13, 49, 57, 312874, tzinfo=utc)),
        ),
    ]
